version: '3.5'

services:
  db:
    build: ./Server/.mongo/
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    build: ./Server/
    depends_on:
      - db
    ports: 
      - 4000:4000
    volumes:
      - .:/opt/server
  client:
    build: ./Client/
    ports:
      - 4200:4200
    volumes:
      - .:/opt/client
volumes:
  mongodb: